const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const WEB=path.join(__dirname,'../src/missing_angle/web'),CT=require(path.join(WEB,'projection-core.js'));
const data=key=>JSON.parse(fs.readFileSync(path.join(WEB,'projection-data',key+'.json'),'utf8'));
function reconstruct(input,views=360,passes=3){const n=96,selected=CT.selectViews(input.angles_deg.length,views,'spread'),order=CT.viewOrder(selected),image=new Float64Array(n*n),cache=new Map();let baseline;for(let p=0;p<=passes;p++){for(const v of order){if(!cache.has(v))cache.set(v,CT.matrixForView(input,n,v));CT.update(cache.get(v),image,input.sinogram[v]);}if(!p)baseline=image.slice();else CT.smooth(image,n,.03);}return {image,baseline,cache,selected,order};}
function rmse(a,b){return Math.sqrt(a.reduce((s,v,i)=>s+(v-b[i])**2,0)/a.length);}
function correlation(a,b){const ma=a.reduce((s,v)=>s+v,0)/a.length,mb=b.reduce((s,v)=>s+v,0)/b.length;let xy=0,xx=0,yy=0;for(let i=0;i<a.length;i++){xy+=(a[i]-ma)*(b[i]-mb);xx+=(a[i]-ma)**2;yy+=(b[i]-mb)**2;}return xy/Math.sqrt(xx*yy);}

test('physical ray lengths agree with square chord geometry',()=>{const g={fov_mm:64};for(const [ray,length]of [[[-100,0,100,0],64],[[0,-100,0,100],64],[[-100,-100,100,100],64*Math.sqrt(2)]]){const [idx,w]=CT.traceRay(g,64,ray);assert(Math.abs(w.reduce((s,v)=>s+v,0)-length)<1e-10);assert(idx.every(i=>i>=0&&i<4096));}assert.equal(CT.traceRay(g,64,[-100,100,100,100])[0].length,0);});

test('independent analytic disk converges with finer pixel resolution',()=>{const g={type:'parallel',fov_mm:64,detector_spacing_mm:1},count=63,errors=[];for(const size of [64,128]){const input={geometry:g,angles_deg:[23],sinogram:[Array(count).fill(0)]},matrix=CT.matrixForView(input,size,0),image=Float64Array.from({length:size*size},(_,k)=>{const x=((k%size)+.5)*64/size-32,y=32-(Math.floor(k/size)+.5)*64/size;return Math.hypot(x,y)<20?1:0;}),observed=CT.forward(matrix,image),truth=Array.from({length:count},(_,d)=>2*Math.sqrt(Math.max(0,400-(d-31)**2)));errors.push(rmse(observed,truth));}assert(errors[1]<errors[0]);assert(errors[1]<.5);});

test('fan geometry and the adjoint agree independently',()=>{const d=data('ta'),m=CT.matrixForView(d,64,97),x=Float64Array.from({length:4096},(_,i)=>Math.sin(i*.13)),y=Float64Array.from({length:140},(_,i)=>Math.cos(i*.3)),ax=CT.forward(m,x),aty=new Float64Array(4096);for(let r=0;r<140;r++)for(let j=m.ptr[r];j<m.ptr[r+1];j++)aty[m.index[j]]+=m.weight[j]*y[r];const left=ax.reduce((s,v,i)=>s+v*y[i],0),right=x.reduce((s,v,i)=>s+v*aty[i],0);assert(Math.abs(left-right)<1e-9);const end=CT.rayEndpoints(d.geometry,0,69.5,140);assert.deepEqual(end,[0,-410.66,0,553.74-410.66]);});

test('strict input checks and view budget prevent malformed acquisitions',()=>{const d=data('ta');assert.equal(CT.validate(d).angles_deg.length,721);for(const mutate of [x=>x.sinogram.pop(),x=>x.sinogram[0][0]=NaN,x=>x.geometry.type='cone',x=>x.geometry.source_distance_mm=10,x=>x.angles_deg[0]='0']){const bad=structuredClone(d);mutate(bad);assert.throws(()=>CT.validate(bad));}for(const n of [4,90,360,721]){const selected=CT.selectViews(721,n,'spread'),order=CT.viewOrder(selected);assert.equal(new Set(order).size,n);assert.deepEqual([...order].sort((a,b)=>a-b),selected);assert.deepEqual(order,CT.viewOrder(selected));}});

const reference=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/htc_reference.json'),'utf8'));
for(const key of ['ta','tb','tc'])test(`360 actual views reconstruct object ${key} against the authors' independent FBP reference`,()=>{const d=CT.validate(data(key)),r=reconstruct(d),ref=reference[key].reference;assert(correlation(r.image,ref)>.98);assert(rmse(r.image,ref)<.004);assert(r.image.some((v,i)=>Math.abs(v-r.baseline[i])>1e-5));assert(r.image.every(v=>Number.isFinite(v)&&v>=0));});

test('repeat calculations are identical and withholding data isolates the solver',()=>{const d=data('ta'),a=reconstruct(d,30,1),b=reconstruct(d,30,1);assert.deepEqual(a.image,b.image);const changed=structuredClone(d),used=new Set(a.selected);for(let i=0;i<changed.sinogram.length;i++)if(!used.has(i))changed.sinogram[i]=changed.sinogram[i].map(v=>v*.25);assert.deepEqual(a.image,reconstruct(changed,30,1).image);changed.sinogram[a.selected[0]]=changed.sinogram[a.selected[0]].map(v=>v*.25);assert.notDeepEqual(a.image,reconstruct(changed,30,1).image);});

test('worker supports pause, one-view stepping and complete measured reconstruction',async()=>{const input=data('ta');input.angles_deg=input.angles_deg.slice(0,4);input.sinogram=input.sinogram.slice(0,4);let count=0,stepped=false;await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('worker timeout')),10000);const context=vm.createContext({setTimeout,clearTimeout,onmessage:null,postMessage:m=>{try{if(m.type==='error')throw Error(m.message);if(m.type==='frame'){count++;if(m.done===0){context.onmessage({data:{type:'pause'}});setTimeout(()=>context.onmessage({data:{type:'one'}}),5);}if(m.done===1){stepped=true;assert.equal(count,2);setTimeout(()=>context.onmessage({data:{type:'resume'}}),5);}}if(m.type==='complete'){assert(stepped);assert.equal(m.image.length,4096);assert.equal(m.selected.length,4);assert.equal(count,5);clearTimeout(timeout);resolve();}}catch(e){clearTimeout(timeout);reject(e);}}});vm.runInContext(fs.readFileSync(path.join(WEB,'projection-core.js'),'utf8')+'\n'+fs.readFileSync(path.join(WEB,'projection-worker.js'),'utf8'),context);context.onmessage({data:{type:'start',input,options:{size:64,views:4,selection:'spread',passes:1,smoothing:0},slow:false}});});});

const Study=require(path.join(WEB,'study.js'));
test('paired error statistics detect scale and offset even at perfect correlation',()=>{const s=CT.paired([1,2,3],[3,5,7]);assert.equal(s.correlation,1);assert.equal(s.slope,2);assert.equal(s.intercept,1);assert.equal(s.bias,3);assert.equal(s.mae,3);assert(Math.abs(s.rmse-Math.sqrt(29/3))<1e-12);assert.equal(s.r2,-13.5);assert.equal(CT.paired([0,0],[1,1]).relative,null);assert.equal(CT.paired([1,1],[2,2]).correlation,null);assert.throws(()=>CT.paired([],[]));assert.throws(()=>CT.paired([1],[NaN]));});
test('synthetic analytic projections reconstruct known holes without matched raster discretisation',()=>{const d=CT.validate(Study.synthetic()),ref=Study.syntheticReference().image,r=reconstruct(d);assert.equal(d.kind,'synthetic');assert.equal(d.angles_deg.length,360);assert(!('image' in d));assert(rmse(r.image,ref)<.0025);assert(correlation(r.image,ref)>.98);assert(rmse(r.image,ref)<rmse(r.baseline,ref));assert.deepEqual(d,Study.synthetic());});
test('reference imports reject wrong geometry and label regions survive validation safely',()=>{const d=Study.synthetic(),r=Study.syntheticReference(64);assert.equal(Study.validateReference(r,d).size,64);assert.throws(()=>Study.validateReference({...r,fov_mm:75},d));assert.throws(()=>Study.validateReference({...r,units:'HU'},d));const labels={name:'Run 1',regions:[{name:'Small hole',x:.1,y:.2,w:.3,h:.4}]};assert.deepEqual(Study.validateLabels(labels),labels);assert.throws(()=>Study.validateLabels({name:'bad',regions:[{name:'outside',x:.9,y:0,w:.2,h:1}]}));assert.equal(Study.regionStats([1,2,3,4],[1,1,1,1],{x:0,y:0,w:.5,h:1}).rmse,Math.sqrt(2));assert.deepEqual([...Study.resample([2,2,2,2],4)],Array(16).fill(2));});
test('published real references match independently prepared test oracles and stay outside projection files',()=>{for(const key of ['ta','tb','tc']){const ref=JSON.parse(fs.readFileSync(path.join(WEB,'reference-data',key+'.json'),'utf8'));Study.validateReference(ref,data(key));assert.deepEqual(ref.image,reference[key].reference);assert.equal(ref.source.sha256,reference[key].source_sha256);}});

for(const key of ['chest-64','chest-96','abdomen-400','abdomen-480'])test(`real body CT ${key} reconstructs from independent simulated views with a separate source reference`,()=>{
 const d=CT.validate(data(key)),r=Study.validateReference(JSON.parse(fs.readFileSync(path.join(WEB,'reference-data',key+'.json'),'utf8')),d),ref=Study.resample(r.image,96),full=reconstruct(d,360,1),sparse=reconstruct(d,90,1);
 assert.equal(d.kind,'body_ct_simulated');assert(!('image' in d));assert.equal(d.angles_deg.length,360);assert.equal(d.sinogram[0].length,192);
 assert(correlation(full.image,ref)>.99);assert(rmse(full.image,ref)<.0006);assert(rmse(full.image,ref)<rmse(full.baseline,ref));
 assert(rmse(sparse.image,ref)<rmse(sparse.baseline,ref));assert(rmse(full.image,ref)<rmse(sparse.image,ref));assert.deepEqual(sparse.image,reconstruct(d,90,1).image);
 assert(full.image.every(v=>Number.isFinite(v)&&v>=0));assert(full.image.some((v,k)=>Math.abs(v-full.baseline[k])>1e-5));
});

test('refinement retains one snapshot per completed pass without changing the calculation',async()=>{
 const input=data('ta');input.angles_deg=input.angles_deg.slice(0,4);input.sinogram=input.sinogram.slice(0,4);let refined=0;const expected=new Float64Array(4096),matrices=input.angles_deg.map((_,v)=>CT.matrixForView(input,64,v)),order=CT.viewOrder([0,1,2,3]);
 await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('refinement timeout')),10000);const context=vm.createContext({setTimeout,clearTimeout,onmessage:null,postMessage:m=>{try{if(m.type==='error')throw Error(m.message);if(m.type==='frame'&&m.stage==='refine'){refined++;assert.equal(m.done,m.pass*4);}if(m.type==='complete'&&m.stage==='build'){setTimeout(()=>context.onmessage({data:{type:'refine',passes:6,smoothing:.03}}),0);}else if(m.type==='complete'){for(let p=0;p<=6;p++){for(const v of order)CT.update(matrices[v],expected,input.sinogram[v]);if(p)CT.smooth(expected,64,.03);}assert.equal(refined,6);assert.deepEqual(Array.from(m.image),Array.from(expected));clearTimeout(timeout);resolve();}}catch(e){clearTimeout(timeout);reject(e);}}});vm.runInContext(fs.readFileSync(path.join(WEB,'projection-core.js'),'utf8')+'\n'+fs.readFileSync(path.join(WEB,'projection-worker.js'),'utf8'),context);context.onmessage({data:{type:'start',input,options:{size:64,views:4,selection:'spread',passes:1,smoothing:0},slow:false}});});
});
