/* The UI consumes actual worker snapshots. It never loads a reconstructed answer. */
(function(){
'use strict';
const $=id=>document.getElementById('live-'+id);
let input=null, worker=null, busy=false, paused=false, result=null, frames=[], visited=new Set(), selected=new Set(), page=0, ticket=0, playback=null, refinements=[], pending=[], expected=null, currentPhase='build';
const inputs=['source','file','count','selection','size'];
const fmt=n=>Number(n).toFixed(1).replace(/\.0$/,'');
function stopPlayback(){clearInterval(playback);playback=null;$('replay').textContent='Play calculated steps';}
function error(message){$('error').hidden=!message;$('error').textContent=message||'';}
function status(message){$('status').textContent=message;}
function state(running){busy=running;if(running)CTStudy.hide();for(const id of inputs)$(id).disabled=running;$('start').disabled=running||!input;$('all').disabled=running||!input;$('pause').disabled=!running;$('stop').disabled=!running;$('refine').disabled=running||!result;$('first-pass').disabled=running||!result;$('download').disabled=running||!result;$('download-input').disabled=!input;$('one').disabled=!running||!paused;$('replay').disabled=running||frames.length<2;}
function cancel(){stopPlayback();if(worker)worker.terminate();worker=null;paused=false;$('pause').textContent='Pause';state(false);}
function blank(){CTStudy.reset();result=null;frames=[];refinements=[];pending=[];expected=null;visited.clear();$('history').max=0;$('history').value=0;$('history').disabled=true;$('history-label').textContent='0 saved';$('progress').value=0;$('comparison').hidden=true;$('metrics').textContent='Measurement agreement will appear when a calculation finishes.';$('frame-label').textContent='No reconstruction yet. Press Reconstruct from views.';paint($('image'),new Float32Array(Number($('size').value)**2));}
function paint(canvas,image,scale=1){const n=Math.round(Math.sqrt(image.length));canvas.width=canvas.height=n;const ctx=canvas.getContext('2d'),pixels=ctx.createImageData(n,n),upper=Number($('window').value);for(let k=0;k<image.length;k++){const v=Math.round(255*Math.min(1,Math.max(0,image[k]*scale/upper)));pixels.data[k*4]=pixels.data[k*4+1]=pixels.data[k*4+2]=v;pixels.data[k*4+3]=255;}ctx.putImageData(pixels,0,0);}
function drawProfile(canvas,index,tiny=false){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,values=input.sinogram[index],max=Math.max(.01,...values),pad=tiny?3:22;ctx.clearRect(0,0,w,h);ctx.fillStyle='#f0f5f5';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#007f87';ctx.lineWidth=tiny?1.5:2;ctx.beginPath();values.forEach((v,k)=>{const x=pad+k*(w-2*pad)/(values.length-1),y=h-pad-Math.max(0,v)*(h-2*pad)/max;if(k)ctx.lineTo(x,y);else ctx.moveTo(x,y);});ctx.stroke();if(!tiny){ctx.fillStyle='#526975';ctx.font='13px system-ui';ctx.fillText('0',3,h-pad);ctx.fillText(max.toFixed(2),3,15);ctx.fillText('Detector position',w/2-50,h-3);}}
function drawSino(){const canvas=$('sinogram'),n=input.angles_deg.length,d=input.sinogram[0].length;canvas.width=n;canvas.height=d;const ctx=canvas.getContext('2d'),p=ctx.createImageData(n,d);let max=0;for(const row of input.sinogram)for(const v of row)max=Math.max(max,v);for(let a=0;a<n;a++)for(let k=0;k<d;k++){const j=(k*n+a)*4,v=Math.round(255*Math.max(0,input.sinogram[a][k])/Math.max(.01,max));p.data[j]=p.data[j+1]=p.data[j+2]=v;p.data[j+3]=255;}ctx.putImageData(p,0,0);canvas.setAttribute('aria-label',`All ${n} projection views, each with ${d} detector readings. Use the view slider to inspect individual angles.`);}
function drawOrbit(){
 const canvas=$('orbit'),ctx=canvas.getContext('2d'),side=260,ratio=Math.min(3,Math.max(1,window.devicePixelRatio||1)),cx=130,cy=130,r=98;
 canvas.width=canvas.height=Math.round(side*ratio);ctx.setTransform(canvas.width/side,0,0,canvas.height/side,0,0);ctx.clearRect(0,0,side,side);
 ctx.strokeStyle='#d5e1e1';ctx.beginPath();ctx.arc(cx,cy,r,0,2*Math.PI);ctx.stroke();
 for(let i=0;i<input.angles_deg.length;i++){const a=input.angles_deg[i]*Math.PI/180;ctx.strokeStyle=visited.has(i)?'#172f3a':selected.has(i)?'#007f87':'#d5e1e1';ctx.beginPath();ctx.moveTo(cx+Math.sin(a)*r,cy-Math.cos(a)*r);ctx.lineTo(cx+Math.sin(a)*(r+8),cy-Math.cos(a)*(r+8));ctx.stroke();}
 const i=Number($('view').value),a=input.angles_deg[i]*Math.PI/180;ctx.strokeStyle='#bc5935';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(cx+Math.sin(a)*(r+17),cy-Math.cos(a)*(r+17));ctx.lineTo(cx-Math.sin(a)*r,cy+Math.cos(a)*r);ctx.stroke();
 $('orbit-count').textContent=`${visited.size} / ${selected.size}`;
}
function inspect(index){if(!input)return;index=Math.max(0,Math.min(input.angles_deg.length-1,index));$('view').value=index;$('view-label').textContent=`${index+1} of ${input.angles_deg.length}`;$('angle-label').textContent=`View ${index+1} · ${fmt(input.angles_deg[index])}°`;$('profile').setAttribute('aria-label',`Measured detector profile at ${fmt(input.angles_deg[index])} degrees`);drawProfile($('profile'),index);drawOrbit();for(const button of $('gallery').querySelectorAll('button'))button.setAttribute('aria-pressed',Number(button.dataset.index)===index?'true':'false');}
function select(){if(!input)return;const count=Math.max(4,Math.min(input.angles_deg.length,Math.round(Number($('count').value)||4)));$('count').value=count;selected=new Set(CT.selectViews(input.angles_deg.length,count,$('selection').value));const indices=[...selected];$('angle-summary').textContent=`${input.angles_deg.length} available · ${count} selected · ${fmt(input.angles_deg[indices[0]])}° to ${fmt(input.angles_deg[indices.at(-1)])}°. Teal: selected; dark: used; rust line: inspected view.`;drawOrbit();}
function gallery(){if(!input)return;const n=input.angles_deg.length,start=page*12,end=Math.min(n,start+12);$('gallery').replaceChildren();$('page-label').textContent=`Views ${start+1} to ${end} of ${n}`;for(let i=start;i<end;i++){const button=document.createElement('button');button.type='button';button.className='view-tile';button.dataset.index=i;button.setAttribute('aria-pressed',Number($('view').value)===i?'true':'false');button.append(document.createTextNode(`View ${i+1} · ${fmt(input.angles_deg[i])}°`));const c=document.createElement('canvas');c.width=180;c.height=70;c.setAttribute('aria-hidden','true');button.append(c);drawProfile(c,i,true);button.onclick=()=>{$('follow').checked=false;inspect(i);};$('gallery').append(button);}$('page-back').disabled=page===0;$('page-next').disabled=end===n;}
async function useInput(data,imported=false,key=null){cancel();input=CT.validate(data);$('title').textContent=`Build an image from ${input.angles_deg.length} X-ray views`;blank();page=0;$('view').max=input.angles_deg.length-1;$('view').value=0;$('count').max=input.angles_deg.length;$('count').value=Math.min(360,input.angles_deg.length);$('all').textContent=`Use all ${input.angles_deg.length} views`;$('source-info').textContent=`${input.name} · ${input.angles_deg.length} ${input.kind==='measured'?'acquired':input.kind==='synthetic'?'simulated':'supplied'} views · ${input.sinogram[0].length} detector readings per view · ${input.geometry.type==='fan'?'fan beam':'parallel beam'} · ${fmt(input.geometry.fov_mm)} mm field of view.${imported?' Opened locally; file contents are not uploaded.':''}`;$('measurement-caption').textContent=input.kind==='synthetic'?'Each column is one simulated angle. Brightness shows analytically calculated attenuation along the detector.':'Each column is one acquired angle. Brightness shows the measured attenuation along the detector.';CTStudy.useInput(input,key);drawSino();select();inspect(0);gallery();state(false);status('Ready. Inspect the views or start a new reconstruction.');error('');}
async function load(key){const request=++ticket;cancel();input=null;blank();state(false);status('Loading measured projections…');try{const data=key==='synthetic'?CTStudy.synthetic():window.CT_EMBEDDED_DATA?window.CT_EMBEDDED_DATA[key]:await fetch(`projection-data/${key}.json`).then(r=>{if(!r.ok)throw Error('Could not load the test measurements. Please retry.');return r.json();});if(request===ticket)await useInput(data,false,key);}catch(e){if(request===ticket){error(e.message);status('The measurements could not be loaded.');}}}
function showFrame(index){const f=frames[index];if(!f)return;$('history').value=index;$('history-label').textContent=`${index+1} of ${frames.length} snapshots`;paint($('image'),f.image);$('frame-label').textContent=f.stage==='build'?`${f.done} of ${f.total} views incorporated in the first pass${f.view===null?'':` · last view ${f.view+1}, ${fmt(input.angles_deg[f.view])}°`}.`:`Refinement pass ${f.pass} · ${f.done} of ${f.total} view corrections completed.`;$('image').setAttribute('aria-label',$('frame-label').textContent);if(f.view!==null&&$('follow').checked)inspect(f.view);}
function comparison(){if(!result)return;paint($('baseline'),result.baseline);const delta=result.image.map((v,k)=>Math.abs(v-result.baseline[k]));paint($('difference'),delta,10);}
function options(){return CT.settings({size:Number($('size').value),views:Number($('count').value),selection:$('selection').value,passes:Number($('passes').value),smoothing:Number($('smoothing').value)},input.angles_deg.length);}
function begin(){if(!input)return;select();stopPlayback();error('');try{const opt=options();if(opt.size*input.sinogram[0].length*opt.views>14000000)throw Error('This selection is too large for the browser memory budget. Reduce the view count or image size.');CTStudy.reset();if(worker)worker.terminate();const blob=window.CT_WORKER_CODE?URL.createObjectURL(new Blob([window.CT_WORKER_CODE],{type:'text/javascript'})):null;worker=new Worker(blob||'projection-worker.js?v=9');if(blob)URL.revokeObjectURL(blob);worker.onmessage=receive;worker.onerror=e=>{error('The calculation could not finish. Try fewer views or a smaller image.');cancel();};frames=[];visited.clear();result=null;paint($('image'),new Float32Array(opt.size**2));refinements=[];$('comparison').hidden=true;paused=false;$('pause').textContent='Pause';currentPhase='build';state(true);status('Starting from a blank image…');$('progress').value=0;worker.postMessage({type:'start',input,options:opt,slow:$('slow').checked});}catch(e){error(e.message);state(false);}}
function refineWith(recipe){stopPlayback();paused=false;$('pause').textContent='Pause';state(true);currentPhase='refine';refinements.push(recipe);status('Refining the image with the same selected measurements…');worker.postMessage({type:'refine',...recipe});}
function receive(event){const m=event.data;if(m.type==='error'){error(m.message);cancel();return;}if(m.type==='frame'){frames.push(m);if(m.stage==='build'&&m.view!==null)visited.add(m.view);drawOrbit();$('progress').max=m.total;$('progress').value=m.done;$('history').max=frames.length-1;$('history').disabled=false;if($('slow').checked||paused)showFrame(frames.length-1);if(!paused&&(m.done%20===0||m.done===m.total))status(m.stage==='build'?`Calculating: ${m.done} of ${m.total} views used.`:`Refining: ${m.done} of ${m.total} corrections complete.`);}else if(m.type==='scoring'){status('Checking the reconstructed image against the measured rays…');$('pause').disabled=true;$('one').disabled=true;}else if(m.type==='complete'){result=m;CTStudy.show(m);showFrame(frames.length-1);state(false);$('comparison').hidden=m.stage!=='refine';comparison();const observed=m.observed===null?'undefined (all selected readings are zero)':(100*m.observed).toFixed(2)+'%',withheld=m.withheld===null?'No unused views in this selection.':`Unused-view mismatch: ${(100*m.withheld).toFixed(2)}%.`;$('metrics').textContent=`Selected-view mismatch: ${observed}. ${withheld} Relative Euclidean error in projection space.`;if(pending.length){refineWith(pending.shift());return;}let suffix='';if(expected){const max=Math.max(...m.image.map((v,k)=>Math.abs(v-expected[k])));suffix=` Saved-run replay: ${max<=1e-9?'matches within 1e−9':'differs from saved values'} (maximum difference ${max.toExponential(2)}).`;expected=null;}status((m.stage==='build'?'Reconstruction complete. You can now refine it or inspect the calculated steps.':'Refinement complete. Compare the first pass with the updated image.')+suffix);}}
function download(object,name){const url=URL.createObjectURL(new Blob([JSON.stringify(object)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('source').onchange=()=>{const custom=$('source').querySelector('option[value="custom"]');if(custom)custom.remove();load($('source').value);};
$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;try{if(file.size>16*1024*1024)throw Error('The file exceeds the 16 MB limit.');const request=++ticket,data=JSON.parse(await file.text());if(request!==ticket)return;const isRun=data.schema==='ct-reconstruction/1';await useInput(isRun?data.input:data,true);if(isRun){CTStudy.restore(data);const o=CT.settings(data.options,input.angles_deg.length);if(data.algorithm!==CT.VERSION||!Array.isArray(data.refinements)||data.refinements.length>12||!data.refinements.every(r=>Number.isInteger(r.passes)&&r.passes>=1&&r.passes<=6&&typeof r.smoothing==='number'&&r.smoothing>=0&&r.smoothing<=.15)||!Array.isArray(data.image)||data.image.length!==o.size**2||!data.image.every(Number.isFinite))throw Error('The saved reconstruction has unsupported settings or image values.');$('size').value=o.size;$('count').value=o.views;$('selection').value=o.selection;pending=data.refinements.map(r=>({...r}));expected=data.image;select();status('Saved measurements and settings opened. Press Reconstruct to recalculate the saved run.');}let option=$('source').querySelector('option[value="custom"]');if(!option){option=document.createElement('option');option.value='custom';$('source').append(option);}option.textContent=input.name;$('source').value='custom';}catch(e){cancel();input=null;blank();state(false);error(e.message);$('source-info').textContent='No valid measurements are loaded.';status('No input loaded. Select a test dataset or open a valid projection file.');}finally{$('file').value='';}};
for(const id of ['count','selection','size'])$(id).onchange=()=>{pending=[];expected=null;cancel();blank();select();state(false);status('Settings changed. Reconstruct to calculate a new image.');};
$('start').onclick=begin;$('all').onclick=()=>{$('count').value=input.angles_deg.length;$('count').onchange();};
$('pause').onclick=()=>{paused=!paused;worker.postMessage({type:paused?'pause':'resume'});$('pause').textContent=paused?'Continue':'Pause';$('one').disabled=!paused;status(paused?'Paused. Continue or calculate one more view.':'Calculation continuing…');};
$('one').onclick=()=>worker.postMessage({type:'one'});
$('stop').onclick=()=>{cancel();result=null;state(false);$('replay').disabled=frames.length<2;status('Calculation stopped. Partial steps remain available; start again for a complete reconstruction.');};
$('slow').onchange=()=>{if(worker)worker.postMessage({type:'speed',delay:$('slow').checked?12:0});};
$('view').oninput=()=>{$('follow').checked=false;inspect(Number($('view').value));};
$('history').oninput=()=>{stopPlayback();showFrame(Number($('history').value));};
$('window').oninput=()=>{$('window-label').textContent=Number($('window').value).toFixed(3)+' /mm';showFrame(Number($('history').value));comparison();CTStudy.render();};
$('replay').onclick=()=>{if(playback){stopPlayback();return;}let i=Number($('history').value);if(i>=frames.length-1)i=0;showFrame(i);$('replay').textContent='Pause step playback';playback=setInterval(()=>{i++;if(i>=frames.length){stopPlayback();return;}showFrame(i);},40);};
$('first-pass').onclick=()=>{pending=[];expected=null;begin();};
$('refine').onclick=()=>{expected=null;pending=[];if(refinements.length>=12){error('This run has reached 12 refinement stages. Start a new reconstruction to continue.');return;}refineWith({passes:Number($('passes').value),smoothing:Number($('smoothing').value)});};
$('download-input').onclick=()=>download(input,'ct-projections.json');
$('download').onclick=()=>{if(result)download({schema:'ct-reconstruction/1',algorithm:CT.VERSION,input,options:result.options,selected:result.selected,order:result.order,refinements,image:Array.from(result.image),baseline:Array.from(result.baseline),metrics:{observed:result.observed,withheld:result.withheld},...CTStudy.export(),snapshot_count:frames.length,display_upper_limit:Number($('window').value),notes:'Replaying recomputes every step from measurements. The solver never receives the saved image as input.'},'ct-reconstruction.json');};
$('page-back').onclick=()=>{page--;gallery();};$('page-next').onclick=()=>{page++;gallery();};
$('sinogram').onclick=e=>{if(!input)return;const box=e.currentTarget.getBoundingClientRect();$('follow').checked=false;inspect(Math.floor((e.clientX-box.left)/box.width*input.angles_deg.length));};
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopPlayback();if(busy&&!paused){paused=true;worker.postMessage({type:'pause'});$('pause').textContent='Continue';$('one').disabled=false;}}});
if(matchMedia('(prefers-reduced-motion: reduce)').matches)$('slow').checked=false;
load('ta');
})();
