'use strict';
const byId=id=>document.getElementById(id);
let experiments=[],current=null,timer=null,selection=0;
function stop(){clearInterval(timer);timer=null;byId('play').textContent='Play reconstruction'}
function showStep(step){byId('step').value=step;byId('animation').src=current.frames[step];byId('animation').alt=`Reconstruction after ${step} correction passes`;byId('step-label').textContent=`${step} / ${current.frames.length-1}`;byId('step-explanation').textContent=step===0?'Start with a blank image. Press Play, or move through the steps yourself.':`Pass ${step}: correct the image using all ${current.views} available views, then gently smooth it.`}
async function selectExperiment(){stop();const request=++selection;byId('result').hidden=true;byId('status').textContent='Loading the selected CT images and recorded steps…';const chosen=experiments.find(e=>e.slice===Number(byId('slice').value)&&e.protocol===byId('protocol').value);try{await Promise.all([...chosen.frames,...['original','phantom','fbp','sart','regularized'].map(k=>`${chosen.folder}/${k}.png`)].map(src=>new Promise((resolve,reject)=>{const image=new Image();image.onload=resolve;image.onerror=reject;image.src=src})));if(request!==selection)return;current=chosen;byId('settings-summary').textContent=`${current.views} views · ${current.span}° covered · ${180-current.span}° missing`;byId('lesson').textContent=current.lesson;for(const method of ['original','phantom','fbp','sart','regularized'])byId(method).src=`${current.folder}/${method}.png`;for(const method of ['fbp','sart','regularized'])byId(`${method}-score`).textContent=`Image difference (RMSE): ${current.metrics[method].rmse.toFixed(5)}`;byId('download').href=`${current.folder}/experiment.zip`;byId('experiment-id').textContent=`Saved run ${current.id}`;byId('step').max=current.frames.length-1;showStep(0);byId('status').textContent='';byId('result').hidden=false}catch{if(request===selection)byId('status').textContent='The images could not load. Check your connection, then choose the slice again or refresh the page.'}}
byId('play').onclick=()=>{if(timer){stop();return}if(Number(byId('step').value)===current.frames.length-1)showStep(0);byId('play').textContent='Pause reconstruction';timer=setInterval(()=>{const next=Number(byId('step').value)+1;showStep(Math.min(next,current.frames.length-1));if(next>=current.frames.length-1)stop()},650)};
byId('step').oninput=()=>{stop();showStep(Number(byId('step').value))};
byId('previous').onclick=()=>{stop();showStep(Math.max(0,Number(byId('step').value)-1))};
byId('next').onclick=()=>{stop();showStep(Math.min(current.frames.length-1,Number(byId('step').value)+1))};
byId('slice').onchange=byId('protocol').onchange=selectExperiment;
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});
new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)stop()}).observe(byId('animation'));
fetch('experiments.json').then(r=>{if(!r.ok)throw Error('Missing data');return r.json()}).then(data=>{experiments=data.experiments;for(const index of [...new Set(experiments.map(e=>e.slice))]){const option=document.createElement('option');option.value=index;option.textContent=`Chest slice ${index}`;byId('slice').append(option)}byId('slice').value='80';byId('slice').disabled=byId('protocol').disabled=false;return selectExperiment()}).catch(()=>{byId('status').textContent='The experiment library could not load. Please refresh the page or download the local app from GitHub.'});
